export const ORIGINS = ['human-direct', 'agent-relay', 'agent-autonomous', 'site-agent'] as const;
export type Origin = (typeof ORIGINS)[number];

/** True for messages that arrived through document.modelContext — i.e. the visiting agent. */
export function isAgentOrigin(o: Origin): boolean {
  return o === 'agent-relay' || o === 'agent-autonomous';
}

/**
 * Proof the Worker validated a WebAuthn signature. The token is opaque to the browser,
 * single-use, and bound to one requestId — the browser cannot mint one, only carry one.
 */
export interface Verification { method: 'webauthn'; token: string; at: number }

/**
 * Recorded when a confirmation completed WITHOUT a hardware authenticator — this device
 * genuinely reported none available (isAuthenticatorAvailable() === false, checked live,
 * never cached across the decision) AND PolicyRules.onMissingAuthenticator is
 * 'trusted-click'. `token` is real and server-issued — the Worker mints it and binds it
 * to (requestId, tool) the same way a webauthn token is (see worker/src/index.ts's
 * /api/trusted-click) — but it is NOT a signature and proves no possession of anything.
 * The Worker cannot independently verify a device's own claim that it lacks an
 * authenticator; it can only record that claim, and refuse it when there is direct
 * evidence against it (a credential already registered for that device). This is an
 * AUDITABLE RECORD, not a VERIFIED FACT — do not read a `trusted-click` entry the way a
 * `webauthn` one is read, and do not reuse Verification's shape for it: this project has
 * already been bitten twice by a value that looked like proof but wasn't.
 */
export interface TrustedClickRecord { method: 'trusted-click'; token: string; at: number }

/** Either recognized level of confirmation proof a human-direct entry can carry. */
export type ConfirmationProof = Verification | TrustedClickRecord;

/**
 * The two assurance levels a confirmation can complete at. Named to match
 * ConfirmationProof['method'] exactly, so a proof's own `method` field IS its assurance
 * level — no separate mapping to keep in sync.
 */
export type Assurance = 'webauthn' | 'trusted-click';

export interface LogEntry {
  id: string;
  origin: Origin;
  text: string;
  at: number;
  /** Set only on human-direct entries that affirm a pending request. */
  confirms?: string;
  /** The tool name this confirmation authorizes. Binds one confirmation to one action. */
  confirmsTool?: string;
  /**
   * Present only when a confirmation carries proof — of EITHER assurance level. Absent
   * entirely for the demo's requireHardwareConfirmation:false bypass (a bare click, no
   * proof of any kind) — see session.ts's confirmRequest.
   */
  verification?: ConfirmationProof;
  /** Structured payload from provide_context. */
  context?: Record<string, unknown>;
  /**
   * Set on a site-agent entry written by a TOOL rather than generated by the model.
   * The distinction is load-bearing: the session skips site-agent entries when feeding
   * the model, because it produced them and re-sending would echo. A tool-written one it
   * did NOT produce — and without this flag the model never learns the action completed,
   * so it goes on asking for a confirmation that already happened, directly underneath
   * its own "refund issued" line. Observed live.
   */
  authoredByTool?: boolean;
}

/**
 * The reason codes the policy engine knows how to reason about, as a runtime value —
 * every tool schema's `enum`, the Worker's own validation, and the type below all derive
 * from this one array so they cannot drift apart.
 *
 * Hyphenated, and that spelling is load-bearing: every TOOL name in this registry is
 * snake_case, so `wrong_item` is the natural guess for an agent that never read the enum.
 * Observed live on the deployed demo, back when nothing validated this: `wrong_item` fell
 * through every explicit branch of evaluateReturnEligibility into the change-of-mind tail
 * and produced a confidently-worded denial for a case policy clause 4 covers outright.
 * An unrecognised code must be REJECTED, never quietly resolved to a default.
 */
export const RETURN_REASONS = ['defect', 'changed-mind', 'wrong-item', 'damaged-in-transit'] as const;
export type ReturnReason = (typeof RETURN_REASONS)[number];

/** Narrows caller-supplied input — tool arguments are unvalidated JSON, never a ReturnReason. */
export function isReturnReason(v: unknown): v is ReturnReason {
  return typeof v === 'string' && (RETURN_REASONS as readonly string[]).includes(v);
}

/**
 * 'order-change' is the verdict route for cancelling or redirecting an order — decided by
 * whether it has shipped, not by the returns policy, which has nothing to say about an
 * order that hasn't arrived yet. See eligibility.ts's evaluateOrderChange.
 */
export type EligibilityPath = 'warranty' | 'return' | 'order-change' | 'disclosure' | 'denied';

export interface Eligibility {
  eligible: boolean;
  path: EligibilityPath;
  /** Human-readable clauses that produced the verdict, in order applied. */
  because: string[];
}

export interface OrderItem { itemId: string; sku: string; title: string; price: number }

export interface Order {
  orderId: string;
  placedAt: number;
  deliveredAt: number | null;
  status: string;
  items: OrderItem[];
}

export interface PolicyRules {
  returnWindowDays: number;
  finalSaleSkus: string[];
  warrantyExemptFromWindow: boolean;
  /** Tool names that cannot execute without a confirmation. */
  requiresHumanDirect: string[];
  /**
   * When true (the default and the only safe setting), a gated tool needs a WebAuthn
   * verification, not merely a human-direct entry. Set false only to demonstrate the
   * attack. Read at mount; never rendered as a control.
   */
  requireHardwareConfirmation: boolean;
  /**
   * What happens when a gated tool needs confirmation and the BROWSER REPORTS this
   * device has no platform authenticator (isAuthenticatorAvailable() === false, checked
   * live, never cached) — as opposed to requireHardwareConfirmation: false above, which
   * is the demo's blanket bypass regardless of hardware and accepts a bare click with
   * no proof at all.
   *
   * 'refuse' — the only setting this project ships safe for anything real, and what
   * the widget falls back to whenever this field is absent, though NOT what this
   * deployment's config/policy.ts sets — matches the original behaviour exactly: no
   * authenticator reported, no confirmation, the button is removed.
   *
   * 'trusted-click' permits a weaker, honestly-labelled confirmation — recorded by the
   * Worker as an auditable claim, not a verified fact (see TrustedClickRecord) — and
   * that check runs BEFORE this flag is ever consulted (verify.ts's
   * verifyHumanPresence calls isAuthenticatorAvailable() first and only reads this
   * flag inside the branch where it came back false), so a device the browser reports
   * HAS an authenticator can never be routed through the weaker path no matter how this
   * flag is set — there is no caller-facing switch for that.
   *
   * "The browser reports absent," not "hardware physically absent," is the actual
   * boundary: isAuthenticatorAvailable() swallows a thrown error and returns false, so
   * a device with real hardware whose browser call fails selects the weaker path the
   * same as genuine absence would.
   *
   * SEVERITY, stated plainly (this is not a cosmetic setting): with 'trusted-click' on,
   * /api/act's confirmation gate becomes satisfiable by any caller who first collects a
   * session ticket from /api/session (Origin-checked, unlike /api/trusted-click and
   * /api/act themselves) and then calls /api/trusted-click with it — a forged
   * `Origin: <EXPECTED_ORIGIN>` header and three POSTs, instead of two bare ones. That
   * stops a caller who merely learned the URL, and stops a different site's page from
   * driving it from a real browser; it does NOT stop anyone who opens the demo page and
   * reads the network tab, and it does not stop any non-browser caller willing to set
   * one header. See README.md's "Layered assurance" section for the full account,
   * including why an Origin check on /api/trusted-click itself would not help either.
   *
   * Read at mount, same as requireHardwareConfirmation; never rendered as a control.
   */
  onMissingAuthenticator: 'refuse' | 'trusted-click';
}

export interface Policy { prose: string; rules: PolicyRules }

export type StanceKey = 'policy-bound' | 'concierge' | 'advocate-adversarial';

/**
 * A refusal carries two audiences, kept apart on purpose.
 * `reason` is prose an agent relays to the PERSON verbatim; `agentHint` is guidance for
 * the agent itself. Conflated, as they were, machine instructions end up read aloud to a
 * human and reassurance meant for a human ends up steering a model.
 */
export type GateResult =
  | { ok: true }
  | { ok: false; reason: string; agentHint?: string };

export interface CallContext {
  origin: Origin;
  /** Log cursor this caller last saw; drives transcript piggyback. */
  cursor: string | null;
}

export interface Tool {
  name: string;
  description: string;
  /**
   * What to show a person when the visiting agent calls this, phrased as a completed
   * action: "checked the returns policy". Optional — a tool with none stays silent.
   *
   * This is the WebMCP layer made visible. Without it the agent's tool calls happen in
   * total silence and a reply simply appears after a pause, so the one thing this project
   * is demonstrating is the one thing nobody can see. Deliberately NOT written to the
   * conversation bus: it is narration for the human, not a turn, and putting it on the bus
   * would feed it back into both agents' context as noise.
   */
  activity?: string;
  inputSchema: Record<string, unknown>;
  annotations?: { readOnlyHint?: boolean };
  execute(input: Record<string, unknown>, ctx: CallContext): Promise<unknown>;
}

export interface Product {
  sku: string;
  title: string;
  price: number;
  description: string;
  finalSale: boolean;
}

/**
 * Which gated tool a pending request can be spent on. The gate binds one to the other, so
 * a cancellation a person confirmed can never be redeemed as a refund and vice versa —
 * the same "one confirmation, one action" rule already applies to tool names,
 * applied one level up at the request itself.
 */
export type RequestKind = 'return' | 'cancel' | 'address-change' | 'records-release' | 'disclosure';

export interface PendingRequest {
  requestId: string;
  kind: RequestKind;
  orderId: string;
  /** Return requests only; '' for a whole-order cancellation or redirect. */
  itemId: string;
  /** Return requests only; null for the kinds the returns policy does not judge. */
  reason: ReturnReason | null;
  /**
   * Consumer role that filed this request. One mounted gateway owns exactly one registered
   * visiting WebMCP surface and one site-agent session; another visitor gets another mount
   * and another gateway. The role therefore routes a receipt between those two consumers,
   * but it is never authorization and gates never read it. WebMCP exposes no per-call
   * caller identity inside one surface, so pretending this were one would create a claim
   * the transport cannot support.
   */
  requestedBy?: Origin;
  /** 'address-change' only: where the order should go instead. */
  address?: string;
  /**
   * Free-form qualifier bound INTO the ceremony alongside the subject, for domains whose
   * consent is not one bit. The clinic uses it for release scope: routine records versus
   * a release that also covers restricted ones. Bound at /options time like everything
   * else the person saw, so a page cannot show a narrow release and spend a wide one.
   */
  scope?: string;
  eligibility: Eligibility;
}
